# https://github.com/jenkinsci/helm-charts/tree/main/charts/jenkins
persistence:
  enabled: false
  size: "100Gi"
controller:
  ## To make Jenkins controller publicly available, uncomment three following lines (serviceType and ingress.enabled)
  ## AND CHANGE PASSWORD (controller.jcasc.securityrealm.local.users.password)
  ## To get URL run `kubectl describe svc cassius-jenkins | grep 'LoadBalancer Ingress'` and use port 8080
  #serviceType: LoadBalancer
  #ingress:
  #  enabled: "true"
  customJenkinsLabels:
    - controller
  resources:
    requests:
      cpu: 2000m
      memory: 8192Mi
    limits:
      cpu: 4000m
      memory: 12298Mi
  installPlugins:
    - job-dsl:1.87
    - configuration-as-code:1775.v810dc950b_514
    - kubernetes:4186.v1d804571d5d4
    - startup-trigger-plugin:2.9.4
    - git
    - workflow-job:1385.vb_58b_86ea_fff1
    - workflow-cps
    - junit:1256.v002534a_5f33e
    - workflow-aggregator:596.v8c21c963d92d
    - blueocean:1.27.10
    - ws-cleanup:0.45
    - pipeline-build-step:540.vb_e8849e1a_b_d8
    - test-stability:2.3
    - copyartifact:722.v0662a_9b_e22a_c
  node-selector:
    cassandra.jenkins: controller
  scriptApproval:
    - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods combinations java.util.Collection"
    - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods inspect java.lang.Object"
    - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods putAt java.util.List java.util.List java.lang.Object"  
  JCasC:
    configScripts:
      welcome-message: |
        jenkins:
          systemMessage: Welcome to Apache Cassandra
      test-job: |
        jobs:
          - script: >
              pipelineJob('cassandra') {
                definition {
                  cpsScm {
                    scm {
                      git {
                        remote {
                          url('https://github.com/thelastpickle/cassandra')
                        }
                        branch('mck/18594/5.0')
                        scriptPath('.jenkins/Jenkinsfile')
                      }
                    }
                    lightweight()
                  }
                }
              }
    securityRealm: |-
      local:
        allowsSignup: false
        enableCaptcha: false
        users:
        - id: "admin"
          name: "Jenkins Admin"
          password: "admin"
#          password: "${chart-admin-password}"
    authorizationStrategy: |-
      loggedInUsersCanDoAnything:
        allowAnonymousRead: false
agent:
  disableDefaultAgent: true
  containerCap: 1000
  podTemplates:
    agent-dind: |
      - name: agent-dind
        label: agent-dind cassandra cassandra-arm64
        activeDeadlineSeconds: '0'
        idleMinutes: '3'
        instanceCap: 1000
        instanceCapStr: "1000"
        nodeUsageMode: "NORMAL"
        showRawYaml: 'true'
        slaveConnectTimeout: '30'
        yamlMergeStrategy: override
        containers:
          - name: jnlp
            # https://github.com/jenkinsci/kubernetes-plugin#pipeline-support
            alwaysPullImage: true
            envVars:
              - envVar:
                  key: DOCKER_TLS_CERTDIR
                  value: /certs/client/
              - envVar:
                  key: DOCKER_CERT_PATH
                  value: /certs/client/
              - envVar:
                  key: DOCKER_TLS_VERIFY
                  value: 'true'
              - envVar:
                  key: DOCKER_HOST
                  value: tcp://localhost:2376
            # image: <DOCKER_SLAVE_IMAGE>:latest  # FROM jenkins/inbound-agent, install dockeri cli
            image: hadesarchitect/jenkins-inbound-agent-dind:linux-amd64
            livenessProbe:
              failureThreshold: '0'
              initialDelaySeconds: '0'
              periodSeconds: '0'
              successThreshold: '0'
              timeoutSeconds: '0'
            privileged: 'false'
            resourceRequestCpu: '1'
            resourceLimitCpu: '1'
            resourceRequestMemory: 5Gi
            resourceLimitMemory: 5Gi
            ttyEnabled: 'false'
            workingDir: /home/jenkins/agent
          - name: dind
            alwaysPullImage: 'false'
            envVars:
            - envVar:
                key: DOCKER_TLS_CERTDIR
                value: /certs
            - envVar:
                key: "DOCKER_IPTABLES_LEGACY"
                value: "1"
            image: docker:dind
            args: "--default-address-pool base=192.168.96.0/20,size=24"  # overwrite docker subnet in case of overlapping 
            livenessProbe:
              failureThreshold: '0'
              initialDelaySeconds: '0'
              periodSeconds: '0'
              successThreshold: '0'
              timeoutSeconds: '0'
            privileged: 'true'
            resourceRequestCpu: '2'
            resourceLimitCpu: '2'
            resourceRequestMemory: 12Gi
            resourceLimitMemory: 15Gi
            ttyEnabled: 'false'
            workingDir: /home/jenkins/agent
        volumes:
          - emptyDirVolume:
              memory: 'false'
              mountPath: /var/lib/docker
          - emptyDirVolume:
              memory: 'false'
              mountPath: /certs
